### PR TITLE
Fix comment to supported double quotes not unsupported single quotes

### PR DESCRIPTION
**Pull request by tirsen**

### CODE REVIEW

**Review by amyangfei — COMMENTED** [review]
LGTM

or we can use `GO_FAILPOINTS='failpoint-name=return("1")'`

**Review by amyangfei — APPROVED** [review]

**Review by lonng — APPROVED** [review]

**Comment by tisonkun** [comment]
@tirsen @lonng could you please sign off the CLA so that we can proceed this PR?

**Review by lonng — APPROVED** [review]
lgtm

**Comment by tisonkun** [comment]
@tirsen thanks for your contribution! Although, we should merge code with CLA check passed. So I'm going to push all commits under my name and hope it's ok for you.

**Pull request closed without merging**
